on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set Up Python3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry
        poetry export -o requirements.txt --without-hashes --dev
        pip install -r requirements.txt
    - name: Lint with pylint
      run: |
        pylint --load-plugins=pylint_django --django-settings-module=core.settings --max-line-length=120 -d C0114 -d C0115 -d C0116 -d W0611 -d R0901 --notes= users
    - name: Coverage report
      run: |
        coverage run manage.py test
        coverage report
