on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set Up Python3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install Poetry
      run: |
        python -m pip install --upgrade pip
        pip install poetry
    - name: Set up poetry environment
        run: |
        poetry install
        poetry shell
    - name: Lint with pylint
        run: |
          pylint --load-plugins pylint_django --django-settings-module=test_project.settings --max-line-length=120 --notes=
    - name: Coverage report
        run: |
          coverage run --omit=/*pypoetry*/ manage.py test
